Global:
  model_name: CRNN
  debug: false
  use_gpu: true
  epoch_num: 400
  distributed: false
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_crnn_nom_exp_1.0/
  save_epoch_step: 1
  eval_batch_step: [9570, 957]
  cal_metric_during_train: false
  pretrained_model: null
  checkpoints: null
  character_dict_path: ./utils/dict/nomnaocr.txt
  save_inference_dir:
  use_space_char: false
  max_text_length: &max_text_length 40

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.e-8
  weight_decay: 0.05
  lr:
    name: Cosine
    learning_rate: 0.0001
    warmup_epoch: 5

Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform: null
  Backbone:
    name: CRNN
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
  Head:
    name: CTCHead

Loss:
  name: SoftCTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list:
      - ./train_data/nomna-train-sctc.txt
    ext_op_transform_idx: 1
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - RecConAug:
          prob: 0.5
          ext_data_num: 2
          image_shape:
            - 48
            - 480
            - 3
      - RecAug:
      - SoftCTCLabelEncode: null
      - SVTRRecResizeImg:
          image_shape:
            - 3
            - 48
            - 480
          padding: true
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length
            - connections
  loader:
    shuffle: true
    batch_size_per_card: 32
    drop_last: true
    num_workers: 8
    collate_fn: "SoftCTCListCollator"

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list:
      - ./train_data/nomna-validate.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode: null
      - SVTRRecResizeImg:
          image_shape:
            - 3
            - 48
            - 480
          padding: true
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 32
    num_workers: 4
