Global:
  model_name: SVTRNet
  debug: false
  use_gpu: true
  epoch_num: 20
  distributed: false
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_svtrnet_base_ch_exp_a5.1.3/
  save_epoch_step: 1
  eval_batch_step: [0, 4882]
  cal_metric_during_train: true
  pretrained_model: null
  checkpoints: null
  character_dict_path: ./utils/dict/nomnaocr.txt
  save_inference_dir:
  use_space_char: false
  max_text_length: &max_text_length 40

Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.e-8
  weight_decay: 0.05
  no_weight_decay_name: norm
  one_dim_param_no_weight_decay: True
  lr:
    name: Cosine
    learning_rate: 0.0001
    warmup_epoch: 5

Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform: null
  Backbone:
    name: SVTRNet
    img_size:
      - 48
      - 480
    out_char_num: *max_text_length
    out_channels: 96
    patch_merging: Conv
    drop_rate: 0.2
    last_drop: 0.1
    attn_drop_rate: 0.1
    drop_path_rate: 0.15
    embed_dim: [96, 192, 256]
    depth: [3, 6, 3]
    num_heads: [2, 4, 8]
    mixer:
      [
        "Conv",
        "Conv",
        "Conv",
        "Conv",
        "Conv",
        "Conv",
        "Global",
        "Global",
        "Global",
        "Global",
        "Global",
        "Global",
      ]
    local_mixer: [[7, 11], [7, 11], [7, 11]]
    last_stage: True
    prenorm: True
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
  Head:
    name: CTCHead

Loss:
  name: WfstCTCLoss
  output_beam: 10.0

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list:
      - ./train_data/nomna-train.txt
    ext_op_transform_idx: 1
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - RecConAug:
          prob: 0.5
          ext_data_num: 2
          image_shape:
            - 48
            - 480
            - 3
      - RecAug:
      - CTCLabelEncode: null
      - SVTRRecResizeImg:
          image_shape:
            - 3
            - 48
            - 480
          padding: true
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length
  loader:
    shuffle: true
    batch_size_per_card: 2
    drop_last: true
    num_workers: 1

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list:
      - ./train_data/nomna-validate.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode: null
      - SVTRRecResizeImg:
          image_shape:
            - 3
            - 48
            - 480
          padding: true
      - KeepKeys:
          keep_keys:
            - image
            - label
            - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 16
    num_workers: 8
